### ISSUE TITLE
Error: Cannot find module 'es2015' 

### ISSUE THREAD

**Issue by martinffx** [electrode-io/electrode-archetype-react-app#29]
I'm following the quickstart guide, with node 4.6.0 and when I run `gulp dev` I get the following error:
```
$ npm install
npm WARN package.json electrode@0.0.1 homepage field must start with a protocol.
npm WARN unmet dependency /Users/martinrichards/code/play/electrode/node_modules/electrode-server/node_modules/hapi/node_modules/subtext/node_modules/pez requires boom@'3.x.x' but will load
npm WARN unmet dependency /Users/martinrichards/code/play/electrode/node_modules/electrode-server/node_modules/hapi/node_modules/boom,
npm WARN unmet dependency which is version 4.0.0
$ gulp dev
[14:30:44] Using gulpfile ~/code/play/electrode/gulpfile.js
[14:30:44] Starting 'dev'...
[14:30:44] Starting '.webpack-dev'...
[14:30:44] Finished '.webpack-dev' after 144 μs
[14:30:44] Starting 'server-dev'...
[14:30:44] Starting 'server-watch-$deps$'...
[14:30:44] Starting '.init-bundle.valid.log'...
[14:30:44] Finished '.init-bundle.valid.log' after 1.28 ms
[14:30:44] Finished 'server-watch-$deps$' after 3.36 ms
[14:30:44] Starting 'server-watch'...
[14:30:44] Starting 'generate-service-worker'...
[14:30:44] Finished 'generate-service-worker' after 591 μs
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .etmp/bundle.valid.log /Users/martinrichards/code/play/electrode/server/**/* /Users/martinrichards/code/play/electrode/config/**/*
Entry point configuration is not found, using default entry point...
isomorphic-loader webpack plugin: removed existing config file
  0% compile http://localhost:2992/webpack-dev-server/
webpack result is served from http://localhost:2992/js/
content is served from /Users/martinrichards/code/play/electrode
 10% 0/1 build modules{ [Error: Cannot find module 'babel-preset-es2015'] code: 'MODULE_NOT_FOUND' }
webpack bundle is now VALID but has ERRORS
webpack report is served from http://localhost:2992/reporter
```

And the report: 

```
Hash: fc7ac480532aa0a11bb3
Version: webpack 1.13.2
Time: 5227ms

ERROR in ./client/app.jsx
Module build failed: Error: Cannot find module 'es2015' (While processing preset: "/Users/martinrichards/code/play/electrode/node_modules/electrode-archetype-react-app/node_modules/babel-preset-es2015-loose/index.js")
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/Users/martinrichards/code/play/electrode/node_modules/electrode-archetype-react-app/node_modules/babel-preset-es2015-loose/node_modules/modify-babel-preset/index.js:35:23)
    at Object. (/Users/martinrichards/code/play/electrode/node_modules/electrode-archetype-react-app/node_modules/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/martinrichards/code/play/electrode/node_modules/electrode-archetype-react-app-dev/node_modules/babel-core/lib/transformation/file/options/option-manager.js:301:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/martinrichards/code/play/electrode/node_modules/electrode-archetype-react-app-dev/node_modules/babel-core/lib/transformation/file/options/option-manager.js:269:20)
    at OptionManager.mergePresets (/Users/martinrichards/code/play/electrode/node_modules/electrode-archetype-react-app-dev/node_modules/babel-core/lib/transformation/file/options/option-manager.js:258:10)
```

**Comment by martinffx** [comment]
So after a little reading around, I found this:
```
 babel-preset-es2015-loose

Babel preset for all es2015 plugins, with loose mode enabled where available.

    Deprecation warning

    This project is deprecated for users of Babel v6.13+. It will still be maintained for users of earlier Babel versions. 👍

    The preset that this project is based on, babel-preset-es2015, now supports setting the "loose" option directly. After updating to babel-preset-es2015 v6.13.0 or higher, you can remove 'es2015-loose' from your list of presets and instead use the 'es2015 preset this way:

presets: [ ["es2015", {"loose": true}] ] }```
```

So I'm guessing I've got the latest version of `babel-preset-es2015` when I ran `npm install`.

You need to either lock down an older version of `babel-preset-es2015` or remove it altogether.

**Comment by jchip** [comment]
thanks for reporting this and figuring out the cause.

**Comment by Vadorequest** [comment]
I was about to fill an issue about this...

---
Hello,

I'm following the Getting Started at http://www.electrode.io/docs/get_started.html but I cannot make it work.

I used `yo electrode` which failed at the end when trying to add a git remote or something, didn't seem like a big deal, JFYI.

But now, I'm trying to lauch the app using `gulp dev` and it fails:

```
~/service/www/electrode-sandbox on  master ⌚ 23:22:36
$ gulp dev
[23:26:11] Using gulpfile ~/service/www/electrode-sandbox/gulpfile.js
[23:26:11] Starting 'dev'...
[23:26:11] Starting '.webpack-dev'...
[23:26:11] Finished '.webpack-dev' after 110 μs
[23:26:11] Starting 'server-dev'...
[23:26:12] Starting 'server-watch-$deps$'...
[23:26:12] Starting '.init-bundle.valid.log'...
[23:26:12] Finished '.init-bundle.valid.log' after 434 μs
[23:26:12] Finished 'server-watch-$deps$' after 2.32 ms
[23:26:12] Starting 'server-watch'...
[23:26:12] Starting 'generate-service-worker'...
[23:26:12] Finished 'generate-service-worker' after 466 μs
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .etmp/bundle.valid.log /home/vadorequest/service/www/electrode-sandbox/server/**/* /home/vadorequest/service/www/electrode-sandbox/config/**/*
Entry point configuration is not found, using default entry point...                                                                                                                                              0% compile http://localhost:2992/webpack-dev-server/
webpack result is served from http://localhost:2992/js/
content is served from /home/vadorequest/service/www/electrode-sandbox                                                                                                                                 10% 0/1 build modules{ [Error: Cannot find module 'babel-preset-es2015'] code: 'MODULE_NOT_FOUND' }                                                                                                    webpack bundle is now VALID but has ERRORS
webpack report is served from http://localhost:2992/reporter

```

I went to **http://localhost:2992/reporter**:
```
Hash: fc7ac480532aa0a11bb3
Version: webpack 1.13.2
Time: 4071ms

ERROR in ./client/app.jsx
Module build failed: Error: Cannot find module 'es2015' (While processing preset: "/home/vadorequest/service/www/electrode-sandbox/node_modules/electrode-archetype-react-app/node_modules/babel-preset-es2015-loose/index.js")
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/home/vadorequest/service/www/electrode-sandbox/node_modules/electrode-archetype-react-app/node_modules/babel-preset-es2015-loose/node_modules/modify-babel-preset/index.js:35:23)
    at Object. (/home/vadorequest/service/www/electrode-sandbox/node_modules/electrode-archetype-react-app/node_modules/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/vadorequest/service/www/electrode-sandbox/node_modules/electrode-archetype-react-app-dev/node_modules/babel-core/lib/transformation/file/options/option-manager.js:301:17
    at Array.map (native)
    at OptionManager.resolvePresets (/home/vadorequest/service/www/electrode-sandbox/node_modules/electrode-archetype-react-app-dev/node_modules/babel-core/lib/transformation/file/options/option-manager.js:269:20)
    at OptionManager.mergePresets (/home/vadorequest/service/www/electrode-sandbox/node_modules/electrode-archetype-react-app-dev/node_modules/babel-core/lib/transformation/file/options/option-manager.js:258:10)
```

You should address this issue fast, it's not complicated to fix and anyone trying to follow your Getting Started will end up with something not working.

**Comment by Vadorequest** [comment]
I'm trying to fix it but no luck so far. 

I changed the **electrode-archetype-react-app/config/babel/.babelrc** about the `presets` option as @martinffx mentionned.

```json
{
  "presets": [
    ["es2015", {"loose": true}],
    "react"
  ],
  "plugins": [
    "babel-plugin-transform-object-rest-spread",
    ["babel-plugin-i18n-id-hashing", {
      "varsContainingMessages": ["defaultMessages", "translations"]
    }],
    ["babel-plugin-react-intl", {
      "messagesDir": "./tmp/messages/",
      "enforceDescriptions": true
    }],
    "transform-node-env-inline",
    "lodash",
    "transform-runtime"
  ],
  "env": {
    "production": {
      "plugins": [
        "babel-plugin-transform-react-constant-elements"
      ]
    }
  }
}

```

I got the following debug logs:

```
...
...
  [163] ./client/routes.jsx 502 bytes {0} [built] [1 error]
  [164] ./client/components/home.jsx 3.04 kB {0} [built] [4 errors]
  [165] ./client/actions/index.jsx 354 bytes {0} [built]
  [166] ./client/styles/base.css 96 bytes {0} [built]
  [170] ./client/reducers/index.jsx 620 bytes {0} [built] [1 error]

ERROR in ./client/app.jsx
Module not found: Error: Cannot resolve module 'react-router' in /home/vadorequest/service/www/electrode-sandbox/client
 @ ./client/app.jsx 11:19-42

ERROR in ./client/app.jsx
Module not found: Error: Cannot resolve module 'redux' in /home/vadorequest/service/www/electrode-sandbox/client
 @ ./client/app.jsx 13:13-29

ERROR in ./client/app.jsx
Module not found: Error: Cannot resolve module 'react-redux' in /home/vadorequest/service/www/electrode-sandbox/client
 @ ./client/app.jsx 15:18-40

ERROR in ./client/routes.jsx
Module not found: Error: Cannot resolve module 'react-router' in /home/vadorequest/service/www/electrode-sandbox/client
 @ ./client/routes.jsx 10:19-42

ERROR in ./client/reducers/index.jsx
Module not found: Error: Cannot resolve module 'redux' in /home/vadorequest/service/www/electrode-sandbox/client/reducers
 @ ./client/reducers/index.jsx 5:13-29

ERROR in ./client/components/home.jsx
Module not found: Error: Cannot resolve module 'react-redux' in /home/vadorequest/service/www/electrode-sandbox/client/components
 @ ./client/components/home.jsx 21:18-40

ERROR in ./client/components/home.jsx
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/classCallCheck' in /home/vadorequest/service/www/electrode-sandbox/client/components
 @ ./client/components/home.jsx 5:23-70

ERROR in ./client/components/home.jsx
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/possibleConstructorReturn' in /home/vadorequest/service/www/electrode-sandbox/client/components
 @ ./client/components/home.jsx 9:34-92

ERROR in ./client/components/home.jsx
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in /home/vadorequest/service/www/electrode-sandbox/client/components
 @ ./client/components/home.jsx 13:17-58
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 1.88 kB [rendered]
        [0] ./~/electrode-archetype-react-app-dev/~/css-loader?modules&-autoprefixer!./~/electrode-archetype-react-app-dev/~/postcss-loader!./client/styles/base.css 376 bytes {0} [built]
        [1] ./~/electrode-archetype-react-app-dev/~/css-loader/lib/css-base.js 1.51 kB {0} [built]
```

I must stay I'm stuck already. :/

**Comment by caoyangs** [comment]
@Vadorequest @martinffx What npm version are you guys using? From the logs you pasted it seems you are using 2. Can you try 3? I see the same issue when using npm@2 but with npm@3 it works.

**Comment by martinffx** [comment]
`2.15.9` I'll give 3 a try when I've got a chance...

**Comment by Vadorequest** [comment]
@caoyangs I have no idea, I thought I was using 3 but since I was on an old VM I may have been using 2 instead.
I believe there are a way to throw a warning/error in the package.json, basically enforcing a specific npm version. Or does it only work with the packages? I don't remember. (That would be a smart way to ensure it doesn't happen to other people)

**Comment by Vadorequest** [comment]
Yep, there is a way: http://www.marcusoft.net/2015/03/packagejson-and-engines-and-enginestrict.html

```json
{ "engines" : { "npm" : ">3" } }
```

I guess adding this to the `package.json` would do the trick! (not tested)

**Comment by martinffx** [comment]
Tested and working with 3!

**Comment by Vadorequest** [comment]
Same for me. :)
